#ifndef _MESHDONGLE_H_
#define _MESHDONGLE_H_

/* Generated by WriteClassHeaderVisitor: Mon May 14 2018 09:49:40 GMT-0600 (Mountain Summer Time) */

#ifdef INCLUDE_PRIVATE
typedef struct _PhidgetMeshDongle *PhidgetMeshDongleHandle;

/* Methods */
API_PRETURN_HDR PhidgetMeshDongle_create(PhidgetMeshDongleHandle *ch);
API_PRETURN_HDR PhidgetMeshDongle_delete(PhidgetMeshDongleHandle *ch);

/* Properties */

/* Events */

#endif /* INCLUDE_PRIVATE */
#endif /* _MESHDONGLE_H_ */
